# Generated by Django 5.2 on 2025-05-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(max_length=10, verbose_name='Código númerico do produto')),
                ('descricao', models.CharField(blank=True, max_length=4000, verbose_name='Descrição/nome do material')),
                ('saldo', models.IntegerField(verbose_name='Quantidade do material em estoque')),
            ],
            options={
                'ordering': ['codigo', 'descricao', 'saldo'],
            },
        ),
    ]
