# Generated by Django 5.2 on 2025-05-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultaOracle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='codigo',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Código númerico do produto'),
        ),
    ]
