# Generated by Django 5.2 on 2025-05-04 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultaOracle', '0002_alter_material_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='codigo',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Código númerico do produto'),
        ),
    ]
