# Generated by Django 5.2 on 2025-05-05 04:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultaOracle', '0003_alter_material_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consumo', models.DateTimeField(default=django.utils.timezone.now)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultaOracle.material')),
            ],
        ),
    ]
