# Generated by Django 5.2 on 2025-05-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultaOracle', '0004_consumo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='consumo',
            new_name='ConsumoMaterial',
        ),
        migrations.RenameField(
            model_name='consumomaterial',
            old_name='fecha_consumo',
            new_name='dataConsumo',
        ),
        migrations.RenameField(
            model_name='consumomaterial',
            old_name='material',
            new_name='materialUsado',
        ),
    ]
